# -*- coding: utf-8 -*-
"""pdf一括取得.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lxesx6iTEvceUDYsnRQ8V_zkioCSAq6

# 日々の天気図
https://www.data.jma.go.jp/yoho/hibiten/index.html
からの一括取得
"""

import requests
import os

year = [str(i) for i in range(2002,2025)]
month = [str(i).zfill(2) for i in range(1,13)]

root_url = 'https://www.data.jma.go.jp/fcd/yoho/data/hibiten/'
#https://www.data.jma.go.jp/fcd/yoho/data/hibiten/2022/2201.pdf

pdf_urls = []
for y in year:
  for m in month:
    pdf_urls.append(root_url + y + '/' + y[-2:] + m + '.pdf')

root_dir = './pdf/'

for url in pdf_urls:
    response = requests.get(url)
    if response.status_code == 200:
        # URLからファイル名を取得
        filename = root_dir + url.split("/")[-1]
        # ファイルをローカルに保存
        with open(filename, 'wb') as f:
            f.write(response.content)
        print(f"{filename} をダウンロードしました。")
    else:
        print(f"{url} からファイルをダウンロードできませんでした。")
print("すべてのダウンロードが完了しました。")